/**
 * routes.js: Word belgesindeki tüm verileri ve ana hub rotalarını içeren genişletilmiş liste.
 * Format: "Havalimanı Adı (KOD), Ülke"
 * Veriler: Mesafe ve Sınıf Bazlı Günlük Pazar Talebi (Demand).
 */

const popularRoutes = [
    { origin: "Belize City (BZE), Belize", destination: "Pointe-à-Pitre (PTP), Guadeloupe", distance: 2850, demand: { y: 2414, j: 274, f: 153 } },
    { origin: "Kuala Lumpur (KUL), Malaysia", destination: "Gaborone (GBE), Botswana", distance: 8705, demand: { y: 2403, j: 258, f: 176 } },
    { origin: "Asmara (ASM), Eritrea", destination: "Pointe-à-Pitre (PTP), Guadeloupe", distance: 10607, demand: { y: 2389, j: 248, f: 141 } },
    { origin: "Nairobi Int (NBO), Kenya", destination: "Bangui (BGF), Central African Republic", distance: 2142, demand: { y: 2373, j: 306, f: 140 } },
    { origin: "Hagåtña (GUM), Guam", destination: "Seoul Incheon (ICN), South Korea", distance: 3227, demand: { y: 2352, j: 273, f: 172 } },
    { origin: "Seattle Tacoma (SEA), United States", destination: "Kingston (KIN), Jamaica", distance: 5264, demand: { y: 2349, j: 250, f: 161 } },
    { origin: "Dallas-Fort Worth (DFW), United States", destination: "Wallis Island (WLS), Wallis and Futuna", distance: 9821, demand: { y: 2347, j: 266, f: 149 } },
    { origin: "Buenos Aires Int (EZE), Argentina", destination: "Bishkek (FRU), Kyrgyzstan", distance: 15905, demand: { y: 2340, j: 243, f: 138 } },
    { origin: "Beirut (BEY), Lebanon", destination: "Yaoundé Nsimalen (NSI), Cameroon", distance: 4164, demand: { y: 2338, j: 262, f: 138 } },
    { origin: "Rabat (RBA), Morocco", destination: "Dakar L.S. Senghor (DSS), Senegal", distance: 2403, demand: { y: 2329, j: 264, f: 148 } },
    { origin: "Seoul Incheon (ICN), South Korea", destination: "Singapore (SIN), Singapore", distance: 4627, demand: { y: 2329, j: 267, f: 159 } },
    { origin: "Charlotte (CLT), United States", destination: "Shanghai Hongqiao (SHA), China", distance: 12272, demand: { y: 2328, j: 308, f: 159 } },
    { origin: "Washington Dulles (IAD), United States", destination: "Funafuti (FUN), Tuvalu", distance: 11754, demand: { y: 2328, j: 287, f: 159 } },
    { origin: "Reykjavík - Keflavik (KEF), Iceland", destination: "Copenhagen (CPH), Denmark", distance: 2144, demand: { y: 2326, j: 304, f: 148 } },
    { origin: "Luanda (LAD), Angola", destination: "Freetown (FNA), Sierra Leone", distance: 3513, demand: { y: 2318, j: 279, f: 137 } },
    { origin: "Khartoum (KRT), Sudan", destination: "Tarawa (TRW), Kiribati", distance: 15292, demand: { y: 2313, j: 344, f: 147 } },
    { origin: "Prishtina (PRN), Kosovo", destination: "Yangon (RGN), Burma", distance: 7538, demand: { y: 2312, j: 259, f: 136 } },
    { origin: "Dar es Salaam (DAR), Tanzania", destination: "Sydney intl (SYD), Australia", distance: 11560, demand: { y: 2306, j: 288, f: 169 } },
    { origin: "Dallas-Fort Worth (DFW), United States", destination: "Dublin (DUB), Ireland", distance: 7180, demand: { y: 2301, j: 321, f: 146 } },
    { origin: "Warsaw intl (WAW), Poland", destination: "Rabat (RBA), Morocco", distance: 2987, demand: { y: 2298, j: 260, f: 146 } },
    { origin: "Havana Int (HAV), Cuba", destination: "Caracas (CCS), Venezuela", distance: 2139, demand: { y: 2298, j: 325, f: 157 } },
    { origin: "Aqaba (AQJ), Jordan", destination: "Singapore (SIN), Singapore", distance: 7909, demand: { y: 2294, j: 266, f: 168 } },
    { origin: "Astana (NQZ), Kazakhstan", destination: "Shenzhen (SZX), China", distance: 4810, demand: { y: 2287, j: 252, f: 191 } },
    { origin: "Asmara (ASM), Eritrea", destination: "Dublin (DUB), Ireland", distance: 5772, demand: { y: 2284, j: 240, f: 145 } },
    { origin: "Bucharest Baneasa (BBU), Romania", destination: "Dubai (DXB), United Arab Emirates", distance: 3390, demand: { y: 2284, j: 246, f: 167 } },
    { origin: "Ouagadougou (OUA), Burkina Faso", destination: "Maseru (MSU), Lesotho", distance: 5598, demand: { y: 2281, j: 256, f: 134 } },
    { origin: "Bucharest Henri Coanda (OTP), Romania", destination: "Oranjestad (AUA), Aruba", distance: 9510, demand: { y: 2280, j: 343, f: 156 } },
    { origin: "Willemstad (CUR), Curaçao", destination: "Kinshasa (FIH), Congo (Kinshasa)", distance: 9504, demand: { y: 2266, j: 270, f: 189 } },
    { origin: "Amman Queen Alia (AMM), Jordan", destination: "Gaborone (GBE), Botswana", distance: 6349, demand: { y: 2265, j: 333, f: 133 } },
    { origin: "Khartoum (KRT), Sudan", destination: "Beijing Capital (PEK), China", distance: 8400, demand: { y: 2256, j: 332, f: 133 } },
    { origin: "Tel Aviv Ben G. (TLV), Israel", destination: "Kingstown (SVD), Saint Vincent and the Grenadines", distance: 9792, demand: { y: 2254, j: 255, f: 143 } },
    { origin: "Quito (UIO), Ecuador", destination: "Shenzhen (SZX), China", distance: 17187, demand: { y: 2251, j: 258, f: 224 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Kingston (KIN), Jamaica", distance: 9696, demand: { y: 2246, j: 251, f: 199 } },
    { origin: "Vienna (VIE), Austria", destination: "Dushanbe (DYU), Tajikistan", distance: 4271, demand: { y: 2243, j: 309, f: 132 } },
    { origin: "Apia (APW), Samoa", destination: "London Gatwick (LGW), United Kingdom", distance: 15801, demand: { y: 2241, j: 257, f: 223 } },
    { origin: "Athens (ATH), Greece", destination: "Riga (RIX), Latvia", distance: 2111, demand: { y: 2235, j: 292, f: 142 } },
    { origin: "Amman Queen Alia (AMM), Jordan", destination: "Canberra (CBR), Australia", distance: 13929, demand: { y: 2232, j: 327, f: 186 } },
    { origin: "Papeete (PPT), French Polynesia", destination: "Willemstad (CUR), Curaçao", distance: 9448, demand: { y: 2232, j: 232, f: 131 } },
    { origin: "Kingston (KIN), Jamaica", destination: "Apia (APW), Samoa", distance: 11016, demand: { y: 2229, j: 353, f: 142 } },
    { origin: "Road Town (EIS), British Virgin Islands", destination: "Chengdu (CTU), China", distance: 14427, demand: { y: 2228, j: 291, f: 142 } },
    { origin: "Wellington (WLG), New Zealand", destination: "Caracas (CCS), Venezuela", distance: 13127, demand: { y: 2222, j: 331, f: 141 } },
    { origin: "Saint George's (GND), Grenada", destination: "Tallinn (TLL), Estonia", distance: 8670, demand: { y: 2221, j: 310, f: 141 } },
    { origin: "Cocos (Keeling) Islands (CCK)", destination: "London Heathrow intl (LHR), United Kingdom", distance: 11568, demand: { y: 2220, j: 394, f: 141 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Basseterre (SKB), Saint Kitts and Nevis", distance: 8734, demand: { y: 2219, j: 297, f: 163 } },
    { origin: "Dar es Salaam (DAR), Tanzania", destination: "Amsterdam (AMS), Netherlands", distance: 7345, demand: { y: 2217, j: 321, f: 173 } },
    { origin: "Fort-de-France (FDF), Martinique", destination: "Bangkok Int (BKK), Thailand", distance: 16255, demand: { y: 2216, j: 230, f: 131 } },
    { origin: "Guangzhou (CAN), China", destination: "Lagos (LOS), Nigeria", distance: 11723, demand: { y: 2210, j: 229, f: 130 } },
    { origin: "Dallas-Fort Worth (DFW), United States", destination: "Saipan Island (SPN), Northern Mariana Islands", distance: 11481, demand: { y: 2209, j: 295, f: 162 } },
    { origin: "Nairobi Int (NBO), Kenya", destination: "Vienna (VIE), Austria", distance: 5838, demand: { y: 2209, j: 241, f: 173 } },
    { origin: "Paro (PBH), Bhutan", destination: "Dzaoudzi (DZA), Mayotte", distance: 6529, demand: { y: 2206, j: 256, f: 162 } },
    { origin: "Manama (BAH), Bahrain", destination: "Marigot (DOM), Dominica", distance: 11317, demand: { y: 2205, j: 292, f: 151 } },
    { origin: "Bern (BRN), Switzerland", destination: "Aqaba (AQJ), Jordan", distance: 3050, demand: { y: 2205, j: 291, f: 151 } },
    { origin: "Georgetown (GCM), Cayman Islands", destination: "Saint Peter Port (GCI), Guernsey", distance: 7588, demand: { y: 2203, j: 275, f: 161 } },
    { origin: "Guatemala City (GUA), Guatemala", destination: "Road Town (EIS), British Virgin Islands", distance: 2801, demand: { y: 2200, j: 344, f: 184 } },
    { origin: "Gaborone (GBE), Botswana", destination: "Moroni (HAH), Comoros", distance: 2333, demand: { y: 2196, j: 231, f: 140 } },
    { origin: "Manama (BAH), Bahrain", destination: "Bangkok Int (BKK), Thailand", distance: 5362, demand: { y: 2196, j: 261, f: 183 } },
    { origin: "Ouagadougou (OUA), Burkina Faso", destination: "Shanghai Hongqiao (SHA), China", distance: 12234, demand: { y: 2195, j: 373, f: 150 } },
    { origin: "Kigali (KGL), Rwanda", destination: "Stockholm intl (ARN), Sweden", distance: 6934, demand: { y: 2194, j: 271, f: 219 } },
    { origin: "Managua (MGA), Nicaragua", destination: "Seoul Incheon (ICN), South Korea", distance: 13533, demand: { y: 2194, j: 288, f: 206 } },
    { origin: "Kingston (KIN), Jamaica", destination: "Pyongyang (FNJ), North Korea", distance: 13244, demand: { y: 2194, j: 310, f: 150 } },
    { origin: "Taipei (TPE), Taiwan", destination: "Stockholm intl (ARN), Sweden", distance: 8329, demand: { y: 2193, j: 233, f: 150 } },
    { origin: "Lisbon (LIS), Portugal", destination: "Taipei (TPE), Taiwan", distance: 11237, demand: { y: 2193, j: 270, f: 150 } },
    { origin: "Sarajevo (SJJ), Bosnia and Herzegovina", destination: "N'Djamena (NDJ), Chad", distance: 3538, demand: { y: 2187, j: 277, f: 171 } },
    { origin: "Nicosia (ECN), Cyprus", destination: "Wallis Island (WLS), Wallis and Futuna", distance: 16169, demand: { y: 2187, j: 289, f: 149 } },
    { origin: "Bucharest Baneasa (BBU), Romania", destination: "Xi'an (XIY), China", distance: 6878, demand: { y: 2187, j: 263, f: 129 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Saipan Island (SPN), Northern Mariana Islands", distance: 10689, demand: { y: 2183, j: 341, f: 182 } },
    { origin: "Praia (RAI), Cape Verde", destination: "Beirut (BEY), Lebanon", distance: 6244, demand: { y: 2181, j: 362, f: 182 } },
    { origin: "Hamilton (BDA), Bermuda", destination: "Prishtina (PRN), Kosovo", distance: 7326, demand: { y: 2177, j: 374, f: 159 } },
    { origin: "Georgetown (GCM), Cayman Islands", destination: "Luxembourg (LUX), Luxembourg", distance: 8215, demand: { y: 2175, j: 344, f: 138 } },
    { origin: "Podgorica (TGD), Montenegro", destination: "Maseru (MSU), Lesotho", distance: 8031, demand: { y: 2175, j: 256, f: 170 } },
    { origin: "Kigali (KGL), Rwanda", destination: "Guatemala City (GUA), Guatemala", distance: 13358, demand: { y: 2173, j: 303, f: 138 } },
    { origin: "Buenos Aires Int (EZE), Argentina", destination: "Windhoek Int (WDH), Namibia", distance: 7374, demand: { y: 2172, j: 278, f: 181 } },
    { origin: "Bujumbura (BJM), Burundi", destination: "Burnt Pine (NLK), Norfolk Island", distance: 14323, demand: { y: 2171, j: 228, f: 138 } },
    { origin: "Dar es Salaam (DAR), Tanzania", destination: "Bucharest Baneasa (BBU), Romania", distance: 5862, demand: { y: 2171, j: 339, f: 128 } },
    { origin: "Kabul (KBL), Afghanistan", destination: "Ouagadougou (OUA), Burkina Faso", distance: 7476, demand: { y: 2171, j: 285, f: 204 } },
    { origin: "Podgorica (TGD), Montenegro", destination: "Oranjestad (AUA), Aruba", distance: 9016, demand: { y: 2171, j: 243, f: 128 } },
    { origin: "Kigali (KGL), Rwanda", destination: "Saint Peter Port (GCI), Guernsey", distance: 6519, demand: { y: 2169, j: 274, f: 170 } },
    { origin: "Phoenix Int (PHX), United States", destination: "Tegucigalpa (TGU), Honduras", distance: 3301, demand: { y: 2167, j: 228, f: 138 } },
    { origin: "Ouagadougou (OUA), Burkina Faso", destination: "Stockholm intl (ARN), Sweden", distance: 5499, demand: { y: 2166, j: 251, f: 228 } },
    { origin: "Taipei (TPE), Taiwan", destination: "Guangzhou (CAN), China", distance: 826, demand: { y: 2164, j: 267, f: 148 } },
    { origin: "Cockburn Town (GDT), Turks and Caicos", destination: "Luxembourg (LUX), Luxembourg", distance: 7312, demand: { y: 2163, j: 273, f: 169 } },
    { origin: "Munich (MUC), Germany", destination: "Luanda (LAD), Angola", distance: 6363, demand: { y: 2162, j: 254, f: 169 } },
    { origin: "Malé (MLE), Maldives", destination: "Frankfurt intl (FRA), Germany", distance: 7884, demand: { y: 2161, j: 309, f: 158 } },
    { origin: "Apia (APW), Samoa", destination: "Malabo (SSG), Equatorial Guinea", distance: 18892, demand: { y: 2161, j: 384, f: 137 } },
    { origin: "Yaren District (INU), Nauru", destination: "Port Louis (MRU), Mauritius", distance: 11985, demand: { y: 2159, j: 362, f: 137 } },
    { origin: "Las Vegas (LAS), United States", destination: "Taipei (TPE), Taiwan", distance: 11003, demand: { y: 2157, j: 244, f: 203 } },
    { origin: "Luxembourg (LUX), Luxembourg", destination: "Manzini Mswati (SHO), Swaziland", distance: 8818, demand: { y: 2156, j: 337, f: 180 } },
    { origin: "Tunis (TUN), Tunisia", destination: "Vilnius (VNO), Lithuania", distance: 2286, demand: { y: 2150, j: 259, f: 127 } },
    { origin: "Wellington (WLG), New Zealand", destination: "Marigot (DOM), Dominica", distance: 13953, demand: { y: 2150, j: 340, f: 137 } },
    { origin: "San Francisco (SFO), United States", destination: "Ouagadougou (OUA), Burkina Faso", distance: 11725, demand: { y: 2149, j: 316, f: 127 } },
    { origin: "Brasília (BSB), Brazil", destination: "New Delhi (DEL), India", distance: 14232, demand: { y: 2146, j: 243, f: 202 } },
    { origin: "Conakry (CKY), Guinea", destination: "Saint George's (GND), Grenada", distance: 5263, demand: { y: 2145, j: 339, f: 190 } },
    { origin: "Papeete (PPT), French Polynesia", destination: "Minsk (MSQ), Belarus", distance: 15970, demand: { y: 2145, j: 243, f: 136 } },
    { origin: "Kampala (EBB), Uganda", destination: "Dubai (DXB), United Arab Emirates", distance: 3731, demand: { y: 2143, j: 356, f: 126 } },
    { origin: "Denver Int (DEN), United States", destination: "Wellington (WLG), New Zealand", distance: 12139, demand: { y: 2141, j: 246, f: 146 } },
    { origin: "Dhaka (DAC), Bangladesh", destination: "Shenzhen (SZX), China", distance: 2393, demand: { y: 2141, j: 290, f: 168 } },
    { origin: "Addis Ababa (ADD), Ethiopia", destination: "Taipei (TPE), Taiwan", distance: 8829, demand: { y: 2139, j: 372, f: 167 } },
    { origin: "Bern (BRN), Switzerland", destination: "Monrovia Int (ROB), Liberia", distance: 4835, demand: { y: 2139, j: 236, f: 178 } },
    { origin: "Caracas (CCS), Venezuela", destination: "Minsk (MSQ), Belarus", distance: 9383, demand: { y: 2138, j: 447, f: 136 } },
    { origin: "Kabul (KBL), Afghanistan", destination: "Paro (PBH), Bhutan", distance: 2080, demand: { y: 2136, j: 309, f: 167 } },
    { origin: "Khartoum (KRT), Sudan", destination: "Copenhagen (CPH), Denmark", distance: 4764, demand: { y: 2135, j: 297, f: 189 } },
    { origin: "Kingstown (SVD), St Vincent", destination: "Freetown (FNA), Sierra Leone", distance: 5253, demand: { y: 2132, j: 366, f: 156 } },
    { origin: "Yaren District (INU), Nauru", destination: "Copenhagen (CPH), Denmark", distance: 13466, demand: { y: 2131, j: 264, f: 212 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Dublin (DUB), Ireland", distance: 2579, demand: { y: 2131, j: 264, f: 212 } },
    { origin: "Cairo (CAI), Egypt", destination: "Malabo (SSG), Equatorial Guinea", distance: 3780, demand: { y: 2130, j: 250, f: 237 } },
    { origin: "Beirut (BEY), Lebanon", destination: "Baucau (BCH), Timor-Leste", distance: 10615, demand: { y: 2130, j: 224, f: 135 } },
    { origin: "Belgrade (BEG), Serbia", destination: "Phnom Penh (PNH), Cambodia", distance: 8677, demand: { y: 2130, j: 241, f: 135 } },
    { origin: "Papeete (PPT), French Polynesia", destination: "Kingstown (SVD), St Vincent", distance: 10286, demand: { y: 2130, j: 260, f: 135 } },
    { origin: "Tarawa (TRW), Kiribati", destination: "Dushanbe (DYU), Tajikistan", distance: 11150, demand: { y: 2130, j: 247, f: 224 } },
    { origin: "Vieux Fort (UVF), Saint Lucia", destination: "Paro (PBH), Bhutan", distance: 14436, demand: { y: 2129, j: 247, f: 156 } },
    { origin: "Washington Dulles (IAD), United States", destination: "Caracas (CCS), Venezuela", distance: 3318, demand: { y: 2129, j: 260, f: 135 } },
    { origin: "Praia (RAI), Cape Verde", destination: "Kampala (EBB), Uganda", distance: 6363, demand: { y: 2128, j: 304, f: 156 } },
    { origin: "Barcelona (BCN), Spain", destination: "Hong Kong (HKG), Hong Kong", distance: 10059, demand: { y: 2128, j: 353, f: 125 } },
    { origin: "Papeete (PPT), French Polynesia", destination: "Shenzhen (SZX), China", distance: 11401, demand: { y: 2128, j: 383, f: 145 } },
    { origin: "Guatemala City (GUA), Guatemala", destination: "Shanghai Pudong (PVG), China", distance: 13869, demand: { y: 2128, j: 308, f: 167 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Gaborone (GBE), Botswana", distance: 7954, demand: { y: 2127, j: 417, f: 125 } },
    { origin: "Vieux Fort (UVF), Saint Lucia", destination: "Road Town (EIS), British Virgin Islands", distance: 649, demand: { y: 2126, j: 272, f: 177 } },
    { origin: "Chisinau (KIV), Moldova", destination: "Podgorica (TGD), Montenegro", distance: 918, demand: { y: 2126, j: 275, f: 189 } },
    { origin: "Hamilton (BDA), Bermuda", destination: "Luanda (LAD), Angola", distance: 9418, demand: { y: 2124, j: 288, f: 166 } },
    { origin: "Dubai (DXB), United Arab Emirates", destination: "Guangzhou (CAN), China", distance: 5827, demand: { y: 2124, j: 312, f: 125 } },
    { origin: "Phoenix Int (PHX), United States", destination: "Beijing Capital (PEK), China", distance: 10438, demand: { y: 2124, j: 220, f: 125 } },
    { origin: "Washington Dulles (IAD), United States", destination: "Apia (APW), Samoa", distance: 11357, demand: { y: 2123, j: 253, f: 177 } },
    { origin: "Malé (MLE), Maldives", destination: "Prishtina (PRN), Kosovo", distance: 6697, demand: { y: 2122, j: 362, f: 200 } },
    { origin: "Baucau (BCH), Timor-Leste", destination: "Bissau (OXB), Guinea-Bissau", distance: 15848, demand: { y: 2121, j: 225, f: 145 } },
    { origin: "Ottawa intl (YOW), Canada", destination: "Kingston (KIN), Jamaica", distance: 3047, demand: { y: 2120, j: 421, f: 135 } },
    { origin: "Hanoi (HAN), Vietnam", destination: "Port Louis (MRU), Mauritius", distance: 6985, demand: { y: 2120, j: 220, f: 125 } },
    { origin: "Nairobi Int (NBO), Kenya", destination: "Nadi (NAN), Fiji", distance: 15201, demand: { y: 2118, j: 275, f: 188 } },
    { origin: "Saint-Pierre (FSP), St Pierre and Miquelon", destination: "Castletown (IOM), Isle of Man", distance: 3655, demand: { y: 2118, j: 278, f: 199 } },
    { origin: "Honiara (HIR), Solomon Islands", destination: "Manama (BAH), Bahrain", distance: 12399, demand: { y: 2116, j: 319, f: 145 } },
    { origin: "Taipei (TPE), Taiwan", destination: "El Aaiún (EUN), Western Sahara", distance: 12429, demand: { y: 2116, j: 264, f: 155 } },
    { origin: "Manila (MNL), Philippines", destination: "Monrovia Int (ROB), Liberia", distance: 14179, demand: { y: 2114, j: 245, f: 223 } },
    { origin: "Bangkok Int (BKK), Thailand", destination: "Warsaw intl (WAW), Poland", distance: 8087, demand: { y: 2114, j: 334, f: 134 } },
    { origin: "Minsk (MSQ), Belarus", destination: "Niamey (NIM), Niger", distance: 5030, demand: { y: 2111, j: 305, f: 222 } },
    { origin: "Vienna (VIE), Austria", destination: "Alofi (IUE), Niue", distance: 16734, demand: { y: 2111, j: 338, f: 144 } },
    { origin: "Bujumbura (BJM), Burundi", destination: "Luqa (MLA), Malta", distance: 4622, demand: { y: 2108, j: 325, f: 165 } },
    { origin: "Reykjavík - Keflavik (KEF), Iceland", destination: "Tashkent (TAS), Uzbekistan", distance: 6052, demand: { y: 2107, j: 370, f: 124 } },
    { origin: "Pago Pago (PPG), American Samoa", destination: "Paro (PBH), Bhutan", distance: 11692, demand: { y: 2106, j: 396, f: 134 } },
    { origin: "Cotonou (COO), Benin", destination: "São Tomé (TMS), São Tomé and Principe", distance: 820, demand: { y: 2103, j: 271, f: 124 } },
    { origin: "Belize City (BZE), Belize", destination: "Munich (MUC), Germany", distance: 9279, demand: { y: 2103, j: 290, f: 124 } },
    { origin: "Addis Ababa (ADD), Ethiopia", destination: "Jakarta Soekarno (CGK), Indonesia", distance: 7705, demand: { y: 2101, j: 292, f: 186 } },
    { origin: "Saint-Pierre (FSP), St Pierre and Miquelon", destination: "Vienna (VIE), Austria", distance: 5261, demand: { y: 2101, j: 260, f: 209 } },
    { origin: "Charlotte (CLT), United States", destination: "Gaborone (GBE), Botswana", distance: 13018, demand: { y: 1063, j: 1035, f: 106 } },
    { origin: "Nairobi Int (NBO), Kenya", destination: "Luanda (LAD), Angola", distance: 2753, demand: { y: 898, j: 1034, f: 161 } },
    { origin: "Quito (UIO), Ecuador", destination: "Basseterre (SKB), Saint Kitts and Nevis", distance: 2587, demand: { y: 882, j: 1033, f: 165 } },
    { origin: "Cockburn Town (GDT), Turks and Caicos", destination: "Guangzhou (CAN), China", distance: 15006, demand: { y: 661, j: 1032, f: 239 } },
    { origin: "Minsk (MSQ), Belarus", destination: "Freetown (FNA), Sierra Leone", distance: 6226, demand: { y: 671, j: 1025, f: 233 } },
    { origin: "Ottawa intl (YOW), Canada", destination: "Luxembourg (LUX), Luxembourg", distance: 5859, demand: { y: 561, j: 1024, f: 269 } },
    { origin: "Minsk (MSQ), Belarus", destination: "Vilnius (VNO), Lithuania", distance: 197, demand: { y: 1229, j: 293, f: 543 } },
    { origin: "Asmara (ASM), Eritrea", destination: "Paro (PBH), Bhutan", distance: 5365, demand: { y: 1178, j: 308, f: 542 } },
    { origin: "Wallis Island (WLS), Wallis and Futuna", destination: "Luanda (LAD), Angola", distance: 17347, demand: { y: 1075, j: 237, f: 538 } },
    { origin: "Barcelona (BCN), Spain", destination: "Tunis (TUN), Tunisia", distance: 859, demand: { y: 1243, j: 244, f: 506 } },
    { origin: "Grand Case (SFG), Saint Martin", destination: "Saint Martin (SXM), Sint Maarten", distance: 9, demand: { y: 1012, j: 278, f: 506 } },
    { origin: "Zandery (PBM), Suriname", destination: "Harare (HRE), Zimbabwe", distance: 9802, demand: { y: 1089, j: 247, f: 501 } }
];
